name: Deploy on Github Pages

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
      - name: Install all dependencies
        run: npm ci
      - name: "Run deploy.sh"
        run: deploy.sh
